apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api
spec:
  selector:
    matchLabels:
      app: sales-api
  template:
    metadata:
      labels:
        app: sales-api
    spec:
      containers:
        - name: app
          image: b65b0111-kr1-registry.container.cloud.toast.com/sales-api-amd64:$version
          ports:
          - name: sales-api
            containerPort: 3000
          - name: sales-api-debug
            containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: sales-api
spec:
  selector:
    app: sales-api
  type: NodePort
  ports:
    - name: sales-api
      port: 3000
      targetPort: sales-api
    - name: sales-api-debug
      port: 4000
      targetPort: sales-api-debug