apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api
spec:
  selector:
    matchLabels:
      app: sales-api
  template:
    metadata:
      labels:
        app: sales-api
    spec:
      containers:
        - name: app
          image: b65b0111-kr1-registry.container.cloud.toast.com/sales-api-amd64:$version

---
apiVersion: v1
kind: Service
metadata:
  name: sales-api
spec:
  selector:
    app: sales-api
  type: NodePort
  ports:
    - name: app
      port: 3000
      targetPort: app
    - name: app-debug
      port: 4000
      targetPort: app-debug

#kl apply -n myservice3 -f - <<EOF
#apiVersion: v1
#kind: Service
#metadata:
#  name: sales-api
#spec:
#  selector:
#    app: sales-api
#  type: NodePort
#  ports:
#    - name: app
#      port: 3000
#      targetPort: app
#    - name: app-debug
#      port: 4000
#      targetPort: app-debug
#  EOF